name: repository-dispatch
author: gendloop
description: 'repository-dispatch'

inputs:
# Required
  token:
    description: 'Personal token'
    required: true
    default: ${{ github.token }}
  repo:
    description: 'Repository name'
    required: true
    default: ''
  workflow:
    description: 'Workflow file name without suffix'
    required: true
    default: ''
# Optional
  params:
    description: 'Params to pass'
    required: false
    default: ''
  user:
    description: 'User'
    required: false
    default: 'gendloop'

runs:
  using: 'composite'
  steps:
    - name: post-dispatch
      shell: bash
      run: |
        curl -L \
            -X POST \
            -H 'Accept: application/vnd.github.v3+json' \
            -H "Authorization: Bearer ${{ inputs.token }}" \
            https://api.github.com/repos/${{ inputs.user }}/${{ inputs.repo }}/actions/workflows/${{ inputs.workflow }}.yml/dispatches \
            -d "'${{ inputs.params }}'"
      