name: Repository_Dispatch

permissions:
  contents: write
  actions: write

on: 
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name'
        required: true
        default: ''
      workflow:
        description: 'Workflow file name without suffix'
        required: true
        default: ''
        type: string
      params:
        description: 'Params to pass'
        required: false
        default: ''
        type: string
      user:
        description: 'User'
        required: false
        default: 'gendloop'
        type: string

jobs:
  repository_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: repository-dispatch
        uses: gendloop/repository-dispatch@v1.0.0
        with: 
          token: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}
          repo: ${{ inputs.repo }}
          workflow: ${{ inputs.workflow }}
          params: ${{ inputs.params }}

      